from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from pathlib import Path


class OperationRisk(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    BLOCKED = "blocked"


@dataclass(frozen=True)
class PermissionDecision:
    risk: OperationRisk
    requires_confirmation: bool
    reason: str


class PermissionPolicy:
    def __init__(self, root: Path):
        self.root = root.resolve()

    def evaluate(self, path: Path, operation: str) -> PermissionDecision:
        target = path.resolve()
        relative = self._relative(target)
        if relative == ".env" or relative.startswith(".env/"):
            return PermissionDecision(
                OperationRisk.HIGH,
                True,
                ".env contains secrets and requires explicit confirmation.",
            )
        if operation in {"delete", "move", "overwrite"} and (
            relative.startswith("input/") or relative.startswith("knowledge/")
        ):
            return PermissionDecision(
                OperationRisk.HIGH,
                True,
                "input and knowledge files are user-provided resources.",
            )
        if relative.startswith("work/") or relative.startswith("output/"):
            return PermissionDecision(
                OperationRisk.LOW,
                False,
                "work and output artifacts are generated by Mag.",
            )
        return PermissionDecision(
            OperationRisk.MEDIUM,
            operation in {"delete", "move", "overwrite"},
            "operation may affect workspace files.",
        )

    def _relative(self, path: Path) -> str:
        try:
            return path.relative_to(self.root).as_posix()
        except ValueError:
            return path.as_posix()
