#!/usr/bin/env python3
"""Generate WIRE_PROTOCOL.md from the pydantic models in protocol.py.

DO NOT EDIT WIRE_PROTOCOL.md MANUALLY — it is auto-generated by this script.

Usage::

    python scripts/gen_protocol_doc.py

This writes (or overwrites) ``WIRE_PROTOCOL.md`` at the repository root.
"""
from __future__ import annotations

import inspect
import json
import sys
from pathlib import Path
from typing import Any, get_args, get_origin, Literal, Union

# Ensure src/ is on the path when run as a script.
_REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO / "src"))

from mcm_agent.server.protocol import (  # noqa: E402
    _COMMAND_MAP,
    _EVENT_MAP,
    # Commands
    PingCommand,
    SessionAttachCommand,
    InputSubmitCommand,
    AskAnswerCommand,
    PermissionDecideCommand,
    InterruptCommand,
    ExitCommand,
    # Events
    StepStartedEvent,
    StepFinishedEvent,
    AssistantChunkEvent,
    AssistantTextEvent,
    ToolCallEvent,
    ToolResultEvent,
    OutputTextEvent,
    AskRequestEvent,
    PermissionRequestEvent,
    StageProgressEvent,
    ArtifactEvent,
    ErrorEvent,
    DoneEvent,
    encode_command,
    encode_event,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _python_type_name(annotation: Any) -> str:
    """Return a human-readable type name for a pydantic field annotation."""
    origin = get_origin(annotation)
    args = get_args(annotation)
    if origin is Literal:
        return f'"{args[0]}"'
    if origin is Union:
        non_none = [a for a in args if a is not type(None)]
        return " | ".join(_python_type_name(a) for a in non_none)
    if annotation is type(None):
        return "None"
    if hasattr(annotation, "__name__"):
        return annotation.__name__
    return str(annotation)


def _model_fields_table(cls: type) -> str:
    """Return a markdown table of fields for a pydantic model class."""
    lines = ["| Field | Type | Default | Description |", "|---|---|---|---|"]
    for name, field in cls.model_fields.items():
        ann = cls.__annotations__.get(name, field.annotation)
        type_str = _python_type_name(ann)
        default = ""
        if field.default is not None and not inspect.isclass(field.default):
            default = f"`{field.default!r}`"
        elif field.default_factory is not None:  # type: ignore[attr-defined]
            default = "(factory)"
        doc = (field.description or "").replace("|", "\\|")
        lines.append(f"| `{name}` | `{type_str}` | {default} | {doc} |")
    return "\n".join(lines)


def _command_example(cls: type, type_key: str) -> str:
    """Build a JSON example for encode_command output."""
    # Build minimal kwargs (skip 'type' which has default)
    kwargs: dict[str, Any] = {}
    for name, field in cls.model_fields.items():
        if name == "type":
            continue
        ann = cls.__annotations__.get(name, field.annotation)
        # Pick a plausible example value by type name
        type_name = _python_type_name(ann)
        if "str" in type_name:
            kwargs[name] = f"<{name}>"
        elif "int" in type_name:
            kwargs[name] = 0
        elif "bool" in type_name:
            kwargs[name] = False
        elif "dict" in type_name:
            kwargs[name] = {}
        else:
            kwargs[name] = f"<{name}>"
    instance = cls(**kwargs)
    line = encode_command(instance, id=1)
    data = json.loads(line.strip())
    return json.dumps(data, indent=2, ensure_ascii=False)


def _event_example(cls: type, type_key: str) -> str:
    """Build a JSON example for encode_event output."""
    from pydantic.fields import PydanticUndefined
    kwargs: dict[str, Any] = {}
    for name, field in cls.model_fields.items():
        if name == "type":
            continue
        # Only skip fields that already have a non-PydanticUndefined default
        has_default = field.default is not PydanticUndefined
        has_default_factory = field.default_factory is not None  # type: ignore[attr-defined]
        if has_default or has_default_factory:
            continue  # has a usable default — let pydantic fill it in
        ann = cls.__annotations__.get(name, field.annotation)
        origin = get_origin(ann)
        import builtins
        if origin is dict or ann is dict or (hasattr(builtins, "dict") and ann is builtins.dict):
            kwargs[name] = {}
        else:
            type_name = _python_type_name(ann)
            if "dict" in type_name.lower():
                kwargs[name] = {}
            elif "int" in type_name:
                kwargs[name] = 0
            elif "bool" in type_name:
                kwargs[name] = False
            else:
                kwargs[name] = f"<{name}>"
    instance = cls(**kwargs)
    line = encode_event(instance)
    data = json.loads(line.strip())
    return json.dumps(data, indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Document sections
# ---------------------------------------------------------------------------

def _section_header() -> str:
    return """\
<!-- DO NOT EDIT MANUALLY — generated by scripts/gen_protocol_doc.py -->
# mag Wire Protocol

> This document is **auto-generated** from `src/mcm_agent/server/protocol.py`.
> Run `python scripts/gen_protocol_doc.py` to regenerate.

## Transport

| Property | Value |
|---|---|
| Protocol | NDJSON over TCP loopback `127.0.0.1:<port>` |
| Encoding | UTF-8, one message per line, `\\n` terminated |
| Override | `MAG_HOST` / `MAG_PORT` environment variables |
| Port derivation | Hashed from workspace path (no port clash across workspaces) |

Each message is exactly **one line of JSON** followed by `\\n` (NDJSON / newline-delimited JSON).

---

## Direction convention

| Direction | Format |
|---|---|
| **Client → Server** (commands) | JSON-RPC 2.0 request: `{"jsonrpc":"2.0","id":...,"method":<type>,"params":{...}}` |
| **Server → Client** (events)   | Event envelope: `{"kind":"event","event":{"type":...,...}}` |

The `params.type` field (commands) and `event.type` field (events) are the routing discriminators.

---
"""


def _section_commands() -> str:
    parts = ["## Commands (client → server)\n"]
    parts.append(
        "Commands are JSON-RPC 2.0 requests. "
        "The `method` field equals `params.type`.\n"
    )
    for type_key, cls in _COMMAND_MAP.items():
        doc = inspect.getdoc(cls) or ""
        parts.append(f"### `{type_key}`\n")
        if doc:
            parts.append(f"{doc}\n")
        parts.append(_model_fields_table(cls))
        parts.append("\n**Example:**\n```json")
        parts.append(_command_example(cls, type_key))
        parts.append("```\n")
    return "\n".join(parts)


def _section_events() -> str:
    parts = ["## Events (server → client)\n"]
    parts.append(
        "Events are wrapped in the envelope `{\"kind\":\"event\",\"event\":{...}}`. "
        "The `event.type` field routes to the correct model.\n"
    )
    for type_key, cls in _EVENT_MAP.items():
        doc = inspect.getdoc(cls) or ""
        parts.append(f"### `{type_key}`\n")
        if doc:
            parts.append(f"{doc}\n")
        parts.append(_model_fields_table(cls))
        parts.append("\n**Example:**\n```json")
        parts.append(_event_example(cls, type_key))
        parts.append("```\n")
    return "\n".join(parts)


def _section_footer() -> str:
    return """\
---

## See also

- `src/mcm_agent/server/protocol.py` — pydantic models + codec (source of truth)
- `src/mcm_agent/server/event_bus.py` — asyncio pub/sub + `EventWriter` persistence
- `scripts/gen_protocol_doc.py` — this document's generator
"""


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def generate() -> str:
    return "\n".join([
        _section_header(),
        _section_commands(),
        "---\n",
        _section_events(),
        _section_footer(),
    ])


if __name__ == "__main__":
    out_path = _REPO / "WIRE_PROTOCOL.md"
    doc = generate()
    out_path.write_text(doc, encoding="utf-8")
    print(f"Written {out_path} ({len(doc.splitlines())} lines)")
